/*
 * vks-api API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0-SNAPSHOT
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vks

type NodeGroupImageDto struct {
	Id                string `json:"id,omitempty"`
	Os                string `json:"os,omitempty"`
	KubernetesVersion string `json:"kubernetesVersion,omitempty"`
	Enable            bool   `json:"enable,omitempty"`
}
