/*
 * vks-api API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0-SNAPSHOT
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vks

type NodeGroupDetailDto struct {
	Id                      string                       `json:"id,omitempty"`
	ClusterId               string                       `json:"clusterId,omitempty"`
	Name                    string                       `json:"name,omitempty"`
	Status                  string                       `json:"status,omitempty"`
	NumNodes                int64                        `json:"numNodes,omitempty"`
	ImageId                 string                       `json:"imageId,omitempty"`
	CreatedAt               string                       `json:"createdAt,omitempty"`
	UpdatedAt               string                       `json:"updatedAt,omitempty"`
	FlavorId                string                       `json:"flavorId,omitempty"`
	DiskSize                int32                        `json:"diskSize,omitempty"`
	DiskType                string                       `json:"diskType,omitempty"`
	EnablePrivateNodes      bool                         `json:"enablePrivateNodes,omitempty"`
	SshKeyId                string                       `json:"sshKeyId,omitempty"`
	SecurityGroups          []string                     `json:"securityGroups,omitempty"`
	AutoScaleConfig         *NodeGroupAutoScaleConfigDto `json:"autoScaleConfig,omitempty"`
	UpgradeConfig           *NodeGroupUpgradeConfigDto   `json:"upgradeConfig,omitempty"`
	Labels                  map[string]string            `json:"labels,omitempty"`
	Taints                  []NodeGroupTaintDto          `json:"taints,omitempty"`
	SecondarySubnets        []string                     `json:"secondarySubnets,omitempty"`
	EnabledEncryptionVolume bool                         `json:"enabledEncryptionVolume,omitempty"`
	SubnetId                string                       `json:"subnetId,omitempty"`
}
