/*
 * vks-api API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0-SNAPSHOT
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vks

type KubeconfigDto struct {
	KubeConfig     string `json:"kubeConfig"`
	ExpirationAt   string `json:"expirationAt"`
	ExpirationDays int32  `json:"expirationDays"`
	Status         string `json:"status"`
	RenewalWarning bool   `json:"renewalWarning"`
}
