/*
 * vks-api API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0-SNAPSHOT
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vks

type UpdateNodeGroupDto struct {
	AutoScaleConfig *NodeGroupAutoScaleConfigDto `json:"autoScaleConfig,omitempty"`
	NumNodes        *int32                       `json:"numNodes,omitempty"`
	UpgradeConfig   *NodeGroupUpgradeConfigDto   `json:"upgradeConfig"`
	SecurityGroups  []string                     `json:"securityGroups"`
	ImageId         string                       `json:"imageId"`
	Labels          map[string]string            `json:"labels,omitempty"`
	Taints          []NodeGroupTaintDto          `json:"taints,omitempty"`
}
