/*
 * vks-api API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0-SNAPSHOT
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vks

type ClusterLoggingConfigDto struct {
	Enabled             bool     `json:"enabled"`
	Type_               string   `json:"type,omitempty"`
	OpensearchClusterId string   `json:"opensearchClusterId,omitempty"`
	Username            string   `json:"username,omitempty"`
	Password            string   `json:"password,omitempty"`
	KafkaClusterId      string   `json:"kafkaClusterId,omitempty"`
	KafkaUserId         string   `json:"kafkaUserId,omitempty"`
	AuthenMode          string   `json:"authenMode,omitempty"`
	Components          []string `json:"components,omitempty"`
}
