/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

type CreateMemDbInstanceRequest struct {
	// DB instance name
	Name string `json:"name,omitempty"`
	// Datastore type
	DatastoreType string `json:"datastoreType,omitempty"`
	// Version of datastore type
	DatastoreVersion string `json:"datastoreVersion,omitempty"`
	// Subnet ID
	NetIds []string `json:"netIds,omitempty"`
	// Optional. Config group ID attached to DB instance
	ConfigId string `json:"configId,omitempty"`
	// Set to 'true' if you want to allow public access to the DB instance
	PublicAccess bool `json:"publicAccess,omitempty"`
	// Set to 'true' if you want to enable daily auto backup
	BackupAuto bool `json:"backupAuto,omitempty"`
	// Required if 'backupAuto' is true. Determine how many days your backup will be retained. Minimum 2 days and maximum 14 days
	BackupDuration int32 `json:"backupDuration,omitempty"`
	// Required if 'backupAuto' is true. The time of the day to backup your DB instance.
	BackupTime string `json:"backupTime,omitempty"`
	// Flavor ID
	PackageId string `json:"packageId,omitempty"`
	// Set to 'true' if you want to enable master password. Required ENABLED if 'publicAccess' is true
	RedisPasswordEnabled bool `json:"redisPasswordEnabled,omitempty"`
	// Redis master password. Required if 'redisPasswordEnabled' is true
	RedisPassword string `json:"redisPassword,omitempty"`
	// Set to 'true' if paying with PoC Credit. Auto Payment only.
	Poc bool `json:"poc,omitempty"`
	// Zone ID
	LocateZoneId string `json:"locateZoneId,omitempty"`
}
