/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

import (
	"time"
)

type ConfigGroupVersionDto struct {
	Id                     string                   `json:"id,omitempty"`
	ConfigGroupId          string                   `json:"configGroupId,omitempty"`
	ConfigGroupName        string                   `json:"configGroupName,omitempty"`
	Version                int32                    `json:"version,omitempty"`
	Properties             []ConfigGroupPropertyDto `json:"properties,omitempty"`
	AssociatedClusterIds   []string                 `json:"associatedClusterIds,omitempty"`
	AssociatedClusterNames []string                 `json:"associatedClusterNames,omitempty"`
	PortalUserId           int32                    `json:"portalUserId,omitempty"`
	CreatedAt              time.Time                `json:"createdAt,omitempty"`
}
