/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

import (
	"time"
)

type BackupDatabase struct {
	Id                    string          `json:"id,omitempty"`
	UserId                int32           `json:"userId,omitempty"`
	Name                  string          `json:"name,omitempty"`
	DatabaseId            string          `json:"databaseId,omitempty"`
	Description           string          `json:"description,omitempty"`
	Status                string          `json:"status,omitempty"`
	BackupEnabled         bool            `json:"backupEnabled,omitempty"`
	LatestRecord          time.Time       `json:"latestRecord,omitempty"`
	CreatedAt             time.Time       `json:"createdAt,omitempty"`
	UpdatedAt             time.Time       `json:"updatedAt,omitempty"`
	BackupPolicyId        string          `json:"backupPolicyId,omitempty"`
	BackupDestinationId   string          `json:"backupDestinationId,omitempty"`
	BackupDestination     *BackupLocation `json:"backupDestination,omitempty"`
	Policy                *BackupPolicy   `json:"policy,omitempty"`
	DatabaseDeleted       bool            `json:"databaseDeleted,omitempty"`
	BackupPolicyName      string          `json:"backupPolicyName,omitempty"`
	BackupDestinationName string          `json:"backupDestinationName,omitempty"`
	TotalBackupSize       int64           `json:"totalBackupSize,omitempty"`
}
