/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases and Kafka Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

type EngineVersion struct {
	Name        string `json:"name,omitempty"`
	Type_       string `json:"type,omitempty"`
	VersionName string `json:"versionName,omitempty"`
	Version     string `json:"version,omitempty"`
	LicenseName string `json:"licenseName,omitempty"`
	LicenseDesc string `json:"licenseDesc,omitempty"`
}
