/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

type UpdateDbConfigGroupRequest struct {
	// DB instance ID
	DbInstanceId string `json:"dbInstanceId,omitempty"`
	// New config group ID or set to empty string \"\" to detach current config group
	ConfigId string `json:"configId,omitempty"`
}
