/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

type ZoneInfo struct {
	Uuid        string `json:"uuid,omitempty"`
	Name        string `json:"name,omitempty"`
	Status      string `json:"status,omitempty"`
	ZoneType    string `json:"zoneType,omitempty"`
	IsDefault   bool   `json:"isDefault,omitempty"`
	Description string `json:"description,omitempty"`
	Weight      int32  `json:"weight,omitempty"`
}
