/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

// Delete config
type DeleteDbInstanceConfig struct {
	// Whether to create a final backup before deleting the DB instance.
	CreateFinalBackup bool `json:"createFinalBackup,omitempty"`
	// Whether to delete all existing backups. If 'createFinalBackup' is true, the final backup will be retained.
	DeleteAllBackup bool `json:"deleteAllBackup,omitempty"`
}
