/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

type PostgreStorageType struct {
	Id               string `json:"id,omitempty"`
	Name             string `json:"name,omitempty"`
	Type_            string `json:"type,omitempty"`
	VolumeTypeSku    string `json:"volumeTypeSku,omitempty"`
	Order            int32  `json:"order,omitempty"`
	Status           string `json:"status,omitempty"`
	MinVolumeSize    int32  `json:"minVolumeSize,omitempty"`
	MaxVolumeSize    int32  `json:"maxVolumeSize,omitempty"`
	ZoneId           string `json:"zoneId,omitempty"`
	Iops             int32  `json:"iops,omitempty"`
	Description      string `json:"description,omitempty"`
	VolumeTypeZoneId string `json:"volumeTypeZoneId,omitempty"`
}
