/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

type TopicDto struct {
	Id               string `json:"id,omitempty"`
	ClusterId        string `json:"clusterId,omitempty"`
	Name             string `json:"name,omitempty"`
	Partitions       int32  `json:"partitions,omitempty"`
	Replicas         int32  `json:"replicas,omitempty"`
	RetentionSeconds int64  `json:"retentionSeconds,omitempty"`
	RetentionBytes   int64  `json:"retentionBytes,omitempty"`
	PortalUserId     int32  `json:"portalUserId,omitempty"`
	Status           string `json:"status,omitempty"`
	CreatedAt        string `json:"createdAt,omitempty"`
}
