/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

type DeleteBackupStorageRequest struct {
	// Delete information
	DatabaseInstances []DeleteBackupStorageDetail `json:"databaseInstances,omitempty"`
	// Action. Allowed value: delete
	Action string `json:"action,omitempty"`
	// Backup Storage resource type. Allowed value: dbaas-backup-storage
	ResType string `json:"resType,omitempty"`
}
