/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

type ActionDbInstanceRequest struct {
	// Action DB instance information
	DatabaseInstances []ActionDbInstanceDetail `json:"databaseInstances,omitempty"`
	// Action. Allowed values: start, stop, reboot, detach_replica
	Action string `json:"action,omitempty"`
	// DB instance resource type. Allowed value: dbaas
	ResType string `json:"resType,omitempty"`
}
