/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

// Database name. Currently support 1 database name at creation.
type DatabaseRequest2 struct {
	// Database name
	Name string `json:"name,omitempty"`
}
