/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

type CreateConfigGroupRequest struct {
	// Config Group Name
	Name string `json:"name,omitempty"`
	// Config Group Description
	Description string `json:"description,omitempty"`
	// Config Group Datastore Type. Allowed values: MySQL, PostgreSQL, MariaDB
	DatastoreType string `json:"datastoreType,omitempty"`
	// Version of Datastore Type
	DatastoreVersion string `json:"datastoreVersion,omitempty"`
	// Optional. Currently only available for PostgreSQL. Allowed values: cluster, single_node. Default value: single_node.Config group with a 'cluster' deploy type can only be used with a PostgreSQL Cluster.
	DeployType string `json:"deployType,omitempty"`
}
