/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases and Kafka Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

type ConfigurationParamInfo struct {
	Name            string   `json:"name,omitempty"`
	Max             string   `json:"max,omitempty"`
	Min             string   `json:"min,omitempty"`
	RestartRequired bool     `json:"restartRequired,omitempty"`
	Type_           string   `json:"type,omitempty"`
	Values          []string `json:"values,omitempty"`
	Modifiable      bool     `json:"modifiable,omitempty"`
	Description     string   `json:"description,omitempty"`
}
