/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases and Kafka Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FlavorInfo struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Vcpus int32 `json:"vcpus,omitempty"`
	Ram int32 `json:"ram,omitempty"`
	FlavorId string `json:"flavorId,omitempty"`
	PriceKey string `json:"priceKey,omitempty"`
	ZoneUUID string `json:"zoneUUID,omitempty"`
	ZoneId int32 `json:"zoneId,omitempty"`
	VolumeSize int32 `json:"volumeSize,omitempty"`
	VolumeType string `json:"volumeType,omitempty"`
	MonthlyCost float64 `json:"monthlyCost,omitempty"`
	BackupSize int32 `json:"backupSize,omitempty"`
	PackageSku string `json:"packageSku,omitempty"`
	FamilyType string `json:"familyType,omitempty"`
	PlatformType string `json:"platformType,omitempty"`
	Bandwidth int32 `json:"bandwidth,omitempty"`
	BandwidthUnit string `json:"bandwidthUnit,omitempty"`
}
