/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

import (
	"time"
)

type BackupLocation struct {
	Id                      string                `json:"id,omitempty"`
	UserId                  int32                 `json:"userId,omitempty"`
	BackendId               string                `json:"backendId,omitempty"`
	ProjectId               string                `json:"projectId,omitempty"`
	Name                    string                `json:"name,omitempty"`
	Product                 string                `json:"product,omitempty"`
	Status                  string                `json:"status,omitempty"`
	IsDefault               bool                  `json:"isDefault,omitempty"`
	VaultLock               *interface{}          `json:"vaultLock,omitempty"`
	SoftDeleteConfig        *interface{}          `json:"softDeleteConfig,omitempty"`
	Type_                   string                `json:"type,omitempty"`
	MaxQuota                *BackupMaxQuota       `json:"maxQuota,omitempty"`
	Config                  *BackupLocationConfig `json:"config,omitempty"`
	CreatedAt               time.Time             `json:"createdAt,omitempty"`
	UpdatedAt               time.Time             `json:"updatedAt,omitempty"`
	NumberOfBackupInstances int32                 `json:"numberOfBackupInstances,omitempty"`
}
