/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

type UserDto struct {
	Id                       string   `json:"id,omitempty"`
	ClusterId                string   `json:"clusterId,omitempty"`
	Name                     string   `json:"name,omitempty"`
	ProduceTopicNames        []string `json:"produceTopicNames,omitempty"`
	ProduceAll               bool     `json:"produceAll,omitempty"`
	ConsumeTopicNames        []string `json:"consumeTopicNames,omitempty"`
	ConsumeAll               bool     `json:"consumeAll,omitempty"`
	ProduceConsumeTopicNames []string `json:"produceConsumeTopicNames,omitempty"`
	ProduceConsumeAll        bool     `json:"produceConsumeAll,omitempty"`
	AdminTopicNames          []string `json:"adminTopicNames,omitempty"`
	AdminAll                 bool     `json:"adminAll,omitempty"`
	MtlsAuthen               bool     `json:"mtlsAuthen,omitempty"`
	SaslAuthen               bool     `json:"saslAuthen,omitempty"`
	PortalUserId             int32    `json:"portalUserId,omitempty"`
	OldStatus                string   `json:"oldStatus,omitempty"`
	Status                   string   `json:"status,omitempty"`
	CreatedAt                string   `json:"createdAt,omitempty"`
}
