/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

type KafkaSecurityGroupRule struct {
	Id        string `json:"id,omitempty"`
	RemoteIp  string `json:"remoteIp,omitempty"`
	Port      int32  `json:"port,omitempty"`
	Status    string `json:"status,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
}
