/*
 * vDB API
 *
 * API for working with vDB Instances (Relational Databases, MemoryStore Databases, Kafka Clusters and PostgreSQL Clusters).
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vdbv2

import (
	"time"
)

type BackupPoint struct {
	Id                  string       `json:"id,omitempty"`
	UserId              int64        `json:"userId,omitempty"`
	BackupDatabaseId    string       `json:"backupDatabaseId,omitempty"`
	DatabaseId          string       `json:"databaseId,omitempty"`
	BackupName          string       `json:"backupName,omitempty"`
	Status              string       `json:"status,omitempty"`
	DestinationSnapshot string       `json:"destinationSnapshot,omitempty"`
	CompressedSize      int64        `json:"compressedSize,omitempty"`
	UncompressedSize    int64        `json:"uncompressedSize,omitempty"`
	CreatedAt           time.Time    `json:"createdAt,omitempty"`
	UpdatedAt           time.Time    `json:"updatedAt,omitempty"`
	PolicySnapshot      string       `json:"policySnapshot,omitempty"`
	Destination         *Destination `json:"destination,omitempty"`
	Time                string       `json:"time,omitempty"`
	EngineVersion       string       `json:"engineVersion,omitempty"`
}
