/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

import (
	"time"
)

type NetworkDto struct {
	Cidr        string                `json:"cidr,omitempty"`
	CreatedAt   time.Time             `json:"createdAt,omitempty"`
	DisplayName string                `json:"displayName,omitempty"`
	ElasticIps  []ElasticOfNetworkDto `json:"elasticIps,omitempty"`
	Id          string                `json:"id,omitempty"`
	Status      string                `json:"status,omitempty"`
	Zone        *Zone                 `json:"zone,omitempty"`
}
