/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

import (
	"time"
)

type RouteTableDto struct {
	CreatedAt time.Time   `json:"createdAt,omitempty"`
	Name      string      `json:"name,omitempty"`
	Routes    []RoutesDto `json:"routes,omitempty"`
	Status    string      `json:"status,omitempty"`
	System    bool        `json:"system,omitempty"`
	Uuid      string      `json:"uuid,omitempty"`
	VpcUuid   string      `json:"vpcUuid,omitempty"`
}
