/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

import (
	"time"
)

type HealthMonitor struct {
	CreatedAt           time.Time `json:"createdAt,omitempty"`
	HealthCheckMethod   string    `json:"healthCheckMethod,omitempty"`
	HealthCheckPath     string    `json:"healthCheckPath,omitempty"`
	HealthCheckProtocol string    `json:"healthCheckProtocol,omitempty"`
	HealthyThreshold    int64     `json:"healthyThreshold,omitempty"`
	Interval            int64     `json:"interval,omitempty"`
	PoolId              string    `json:"poolId,omitempty"`
	ProjectId           string    `json:"projectId,omitempty"`
	ProvisioningStatus  string    `json:"provisioningStatus,omitempty"`
	SuccessCode         string    `json:"successCode,omitempty"`
	Timeout             int64     `json:"timeout,omitempty"`
	UnhealthyThreshold  int64     `json:"unhealthyThreshold,omitempty"`
	UpdatedAt           time.Time `json:"updatedAt,omitempty"`
	Uuid                string    `json:"uuid,omitempty"`
}
