/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

// Delete Bandwidth Request
type DeleteBandwidthRequest struct {
	// Id of Bandwidth
	Id string `json:"id"`
	// Ip of Bandwidth
	Ip string `json:"ip"`
}
