/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type CreateRouteTableRequest struct {
	// Name of The route table
	Name string `json:"name"`
	// Uuid of The VPC
	VpcUuid string `json:"vpcUuid"`
}
