/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type K8sVersionDto struct {
	Name   string `json:"name,omitempty"`
	Status string `json:"status,omitempty"`
	Uuid   string `json:"uuid,omitempty"`
	Weight string `json:"weight,omitempty"`
}
