/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type CreateAddressPairRequest struct {
	// Uuid of the network interface
	NetworkInterfaceUuid string `json:"networkInterfaceUuid"`
	// Uuid of the project
	ProjectUuid string `json:"projectUuid"`
	// Uuid of the virtual IP Address
	VirtualIPUuid string `json:"virtualIPUuid"`
}
