/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type Flavor struct {
	Bandwidth              int32  `json:"bandwidth,omitempty"`
	BandwidthUnit          string `json:"bandwidthUnit,omitempty"`
	Cpu                    int32  `json:"cpu,omitempty"`
	CpuPlatformDescription string `json:"cpuPlatformDescription,omitempty"`
	FlavorId               string `json:"flavorId,omitempty"`
	Gpu                    int32  `json:"gpu,omitempty"`
	Group                  string `json:"group,omitempty"`
	Memory                 int32  `json:"memory,omitempty"`
	Name                   string `json:"name,omitempty"`
	RemainingVms           int32  `json:"remainingVms,omitempty"`
	ZoneId                 string `json:"zoneId,omitempty"`
}
