/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type ChangeTypeBandwidthRequest struct {
	DediDomPackageName string `json:"dediDomPackageName,omitempty"`
	DediIntPackageName string `json:"dediIntPackageName,omitempty"`
	Ip                 string `json:"ip,omitempty"`
	UpdateTimestamp    bool   `json:"updateTimestamp,omitempty"`
	Uuid               string `json:"uuid,omitempty"`
}
