/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type SubnetResponse struct {
	ErrorCode int32       `json:"errorCode,omitempty"`
	ErrorMsg  string      `json:"errorMsg,omitempty"`
	Extra     interface{} `json:"extra,omitempty"`
	Subnets   []Subnet    `json:"subnets,omitempty"`
	Success   bool        `json:"success,omitempty"`
}
