/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type RouteRequest struct {
	// Specifies the destination in CIDR notation for the route. This is used to match the destination IP addresses of network traffic.
	DestinationCidrBlock string `json:"destinationCidrBlock"`
	// Unique identifier for the target of the route, such as a virtual machine or a gateway.
	Target string `json:"target"`
}
