/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type TypesItem struct {
	Condition *TypeItemCondition `json:"condition,omitempty"`
	Key       string             `json:"key,omitempty"`
	Value     string             `json:"value,omitempty"`
}
