/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

import (
	"time"
)

type BandwidthModel struct {
	Area                              string    `json:"area,omitempty"`
	BackendEnable                     bool      `json:"backendEnable,omitempty"`
	BackendType                       string    `json:"backendType,omitempty"`
	CreatedAt                         time.Time `json:"createdAt,omitempty"`
	Description                       string    `json:"description,omitempty"`
	Id                                int64     `json:"id,omitempty"`
	Ip                                string    `json:"ip,omitempty"`
	OldSystemBandwidthVolume          string    `json:"oldSystemBandwidthVolume,omitempty"`
	OldSystemBandwidthVolumeUpdatedAt time.Time `json:"oldSystemBandwidthVolumeUpdatedAt,omitempty"`
	PackageDomDedi                    string    `json:"packageDomDedi,omitempty"`
	PackageIntDedi                    string    `json:"packageIntDedi,omitempty"`
	PackagePayg                       string    `json:"packagePayg,omitempty"`
	PackageType                       string    `json:"packageType,omitempty"`
	ProjectUuid                       string    `json:"projectUuid,omitempty"`
	ResourceType                      string    `json:"resourceType,omitempty"`
	Status                            string    `json:"status,omitempty"`
	TotalVolume                       int64     `json:"totalVolume,omitempty"`
	Trash                             int64     `json:"trash,omitempty"`
	UpdatedAt                         time.Time `json:"updatedAt,omitempty"`
	UsedVolume                        int64     `json:"usedVolume,omitempty"`
	UserId                            int64     `json:"userId,omitempty"`
	Uuid                              string    `json:"uuid,omitempty"`
}
