/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type DeleteListenerRequest struct {
	// id of the listener to delete
	ListenerId string `json:"listenerId"`
}
