/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type DataResponseListRoutesDto struct {
	Data []RoutesDto `json:"data,omitempty"`
}
