/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type ClusterNodeDto struct {
	ClusterId   int64       `json:"clusterId,omitempty"`
	DateCreated string      `json:"dateCreated,omitempty"`
	DateDeleted string      `json:"dateDeleted,omitempty"`
	FixedIp     string      `json:"fixedIp,omitempty"`
	FloatingIp  string      `json:"floatingIp,omitempty"`
	IsMaster    int64       `json:"isMaster,omitempty"`
	Name        string      `json:"name,omitempty"`
	NodeGroupId int32       `json:"nodeGroupId,omitempty"`
	ProjectId   int64       `json:"projectId,omitempty"`
	Secgroup    interface{} `json:"secgroup,omitempty"`
	Status      string      `json:"status,omitempty"`
	VmUuid      string      `json:"vmUuid,omitempty"`
}
