/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

// Attach Network Interface Request
type AttachNetworkInterfaceRequest struct {
	// List Id of subnet
	SubnetIds []string `json:"subnetIds,omitempty"`
}
