/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

import (
	"time"
)

type CaDto struct {
	CertificateType string    `json:"certificateType,omitempty"`
	CreatedAt       time.Time `json:"createdAt,omitempty"`
	ExpiredAt       string    `json:"expiredAt,omitempty"`
	Name            string    `json:"name,omitempty"`
	Uuid            string    `json:"uuid,omitempty"`
}
