/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type CreateVirtualIpAddressRequest struct {
	// description for Virtual IP Address.
	Description string `json:"description,omitempty"`
	// Name of the Virtual IP Address
	Name string `json:"name"`
	// Id of the subnet
	SubnetId string `json:"subnetId"`
}
