/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type ReorderPoliciesRequestV2 struct {
	// List of policies to reorder, start from 1 to ....
	Policies []ReorderPolicyRequest `json:"policies"`
}
