/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

import (
	"time"
)

type VirtualIpAddressDto struct {
	AddressPairIps []string  `json:"addressPairIps,omitempty"`
	CreatedAt      time.Time `json:"createdAt,omitempty"`
	Description    string    `json:"description,omitempty"`
	IpAddress      string    `json:"ipAddress,omitempty"`
	Name           string    `json:"name,omitempty"`
	NetworkCIDR    string    `json:"networkCIDR,omitempty"`
	NetworkName    string    `json:"networkName,omitempty"`
	NetworkUuid    string    `json:"networkUuid,omitempty"`
	SubnetCIDR     string    `json:"subnetCIDR,omitempty"`
	SubnetName     string    `json:"subnetName,omitempty"`
	SubnetUuid     string    `json:"subnetUuid,omitempty"`
	Uuid           string    `json:"uuid,omitempty"`
}
