/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type VolumeType struct {
	Id string `json:"id,omitempty"`
	Iops int32 `json:"iops,omitempty"`
	MaxSize int32 `json:"maxSize,omitempty"`
	MinSize int32 `json:"minSize,omitempty"`
	Name string `json:"name,omitempty"`
	ThroughPut int32 `json:"throughPut,omitempty"`
	ZoneId string `json:"zoneId,omitempty"`
}
