/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

import (
	"time"
)

type AddressPairDto struct {
	CreatedAt        time.Time `json:"createdAt,omitempty"`
	NetInterfaceIp   string    `json:"netInterfaceIp,omitempty"`
	NetInterfaceUuid string    `json:"netInterfaceUuid,omitempty"`
	Uuid             string    `json:"uuid,omitempty"`
	VipUuid          string    `json:"vipUuid,omitempty"`
}
