/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type PoolItem struct {
	MonitorPort int32  `json:"monitorPort,omitempty"`
	Name        string `json:"name,omitempty"`
	PoolId      string `json:"poolId,omitempty"`
	Port        int32  `json:"port,omitempty"`
}
