/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type PackageLimit struct {
	Cpu      int32 `json:"cpu,omitempty"`
	DiskSize int32 `json:"diskSize,omitempty"`
	Memory   int32 `json:"memory,omitempty"`
}
