/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type AttachmentEntity struct {
	CreatedAt             *Timestamp `json:"createdAt,omitempty"`
	DeletedAt             *Timestamp `json:"deletedAt,omitempty"`
	Id                    int32      `json:"id,omitempty"`
	InterfaceInstanceUuid string     `json:"interfaceInstanceUuid,omitempty"`
	InterfaceVolumeUuid   string     `json:"interfaceVolumeUuid,omitempty"`
	ProjectId             string     `json:"projectId,omitempty"`
}
