/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

import (
	"time"
)

// Recover Server Request
type RecoverServerRequest struct {
	EndTime time.Time `json:"endTime,omitempty"`
	Extra *interface{} `json:"extra,omitempty"`
	Period int32 `json:"period,omitempty"`
	// Id of server
	ServerId string `json:"serverId"`
	StartTime time.Time `json:"startTime,omitempty"`
	// Id of user
	UserId int32 `json:"userId,omitempty"`
}
