/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type RenewBandwidthRequest struct {
	Ip   string `json:"ip,omitempty"`
	Uuid string `json:"uuid,omitempty"`
}
