/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type SimpleServerTaskDto struct {
	Id string `json:"id,omitempty"`
}
