/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type VolumeTypeZone struct {
	Id   string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
