/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type RouteTableUpdateRouteRequest struct {
	// Id of project
	ProjectId string `json:"projectId,omitempty"`
	// The updated routes list of route-table
	Routes []UpdatedRoute `json:"routes,omitempty"`
	// Id of user
	UserId int32 `json:"userId,omitempty"`
}
