/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type CreateSecurityGroupRuleRequest struct {
	// description for secgoup rule.
	Description string `json:"description,omitempty"`
	// \"ingress\" or \"egress\"
	Direction string `json:"direction"`
	// \"IPV4\" or \"IPv6\"
	Ethertype string `json:"ethertype"`
	// upper bound of range port.
	PortRangeMax int32 `json:"portRangeMax"`
	// upper bound of range port.
	PortRangeMin int32 `json:"portRangeMin"`
	// \"TCP\", \"UDP\", \"ICMP\", ...
	Protocol string `json:"protocol"`
	// Ip Prefix of source/target.
	RemoteIpPrefix string `json:"remoteIpPrefix"`
	// Id of security group that rules are attached.
	SecurityGroupId string `json:"securityGroupId"`
}
