/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type CreateNodeGroupBackendRequest struct {
	// Id of cluster
	ClusterId string `json:"clusterId"`
	// Id of the flavor
	FlavorId string `json:"flavorId"`
	// Name of the node group
	Name string `json:"name"`
	// number of the node in node group
	NodeCount int32 `json:"nodeCount"`
}
