/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

import (
	"time"
)

type Volume struct {
	Action         []string  `json:"action,omitempty"`
	Bootable       bool      `json:"bootable,omitempty"`
	CreatedAt      time.Time `json:"createdAt,omitempty"`
	EncryptionType string    `json:"encryptionType,omitempty"`
	Id             string    `json:"id,omitempty"`
	InstanceUuid   string    `json:"instanceUuid,omitempty"`
	Name           string    `json:"name,omitempty"`
	OwnerEmail     string    `json:"ownerEmail,omitempty"`
	Share          bool      `json:"share,omitempty"`
	Size           int32     `json:"size,omitempty"`
	Status         string    `json:"status,omitempty"`
	VolumeTypeId   string    `json:"volumeTypeId,omitempty"`
}
