/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

// Update Server Request
type UpdateServerRequest struct {
	// Id of server
	ServerId string `json:"serverId"`
}
