/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type UpdateNetworkAclSubnetsRequest struct {
	// Id of project
	ProjectId string `json:"projectId,omitempty"`
	// The updated subnets uuid list of network-acl
	SubnetUuids []string `json:"subnetUuids,omitempty"`
	// Id of user
	UserId int32 `json:"userId,omitempty"`
}
