/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type ServerLimit struct {
	DataDisk *DataDiskLimit `json:"dataDisk,omitempty"`
	RootDisk *RootDiskLimit `json:"rootDisk,omitempty"`
}
