/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

// Detach External Network Interface Request
type DetachExternalNetworkInterfaceRequest struct {
	// Network interface id
	NetworkInterfaceId string `json:"networkInterfaceId,omitempty"`
}
