/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type InternalNetworkInterfaceDto struct {
	FixedIp    string `json:"fixedIp,omitempty"`
	SubnetUuid string `json:"subnetUuid,omitempty"`
	Uuid       string `json:"uuid,omitempty"`
}
