/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

type EditSecurityGroupRequest struct {
	Description string       `json:"description,omitempty"`
	Extra       *interface{} `json:"extra,omitempty"`
	Name        string       `json:"name,omitempty"`
	// Id of Secgroup to be deleted.
	SecgroupId string `json:"secgroupId"`
}
