/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

import (
	"time"
)

type AddressPairDto struct {
	CreatedAt          time.Time `json:"createdAt"`
	NetworkInterfaceId string    `json:"networkInterfaceId"`
	NetworkInterfaceIp string    `json:"networkInterfaceIp"`
	Uuid               string    `json:"uuid"`
	VirtualIpAddressId string    `json:"virtualIpAddressId"`
}
