/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vserver

import (
	"time"
)

type VirtualIpAddressNetworkEntity struct {
	CreatedAt        time.Time `json:"createdAt,omitempty"`
	DeletedAt        time.Time `json:"deletedAt,omitempty"`
	Id               int64     `json:"id,omitempty"`
	NetInterfaceUuid string    `json:"netInterfaceUuid,omitempty"`
	ProjectUuid      string    `json:"projectUuid,omitempty"`
	Uuid             string    `json:"uuid,omitempty"`
	VipUuid          string    `json:"vipUuid,omitempty"`
}
