/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vloadbalancing

import (
	"time"
)

// Import CA Request
type ImportCaRequest struct {
	// Certificate of the CA
	Certificate string `json:"certificate,omitempty"`
	// A certificate chain is an ordered list of certificates, containing an SSL/TLS Certificate and Certificate Authority (CA) Certificates, that enable the receiver to verify that the sender and all CA's are trustworthy.
	CertificateChain string `json:"certificateChain,omitempty"`
	// Expiration of CA
	Expiration time.Time `json:"expiration,omitempty"`
	// Name of the CA
	Name string `json:"name"`
	// The password of the private key.
	Passphrase string `json:"passphrase,omitempty"`
	// Private key of the CA
	PrivateKey string `json:"privateKey,omitempty"`
	// Type of the certificate ( CA or TLS/SSL )
	Type_ string `json:"type"`
}
