/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vloadbalancing

import (
	"github.com/vngcloud/terraform-provider-vngcloud/client/utils"
)

type L7Policy struct {
	Action           string                `json:"action"`
	CreatedAt        utils.JsonParsingDate `json:"createdAt"`
	Description      string                `json:"description"`
	KeepQueryString  bool                  `json:"keepQueryString"`
	L7Rule           *L7Rule               `json:"l7Rule"`
	Name             string                `json:"name"`
	Position         int64                 `json:"position"`
	ProgressStatus   string                `json:"progressStatus"`
	DisplayStatus    string                `json:"displayStatus"`
	RedirectHttpCode int32                 `json:"redirectHttpCode"`
	RedirectPoolId   string                `json:"redirectPoolId"`
	RedirectUrl      string                `json:"redirectUrl"`
	UpdatedAt        utils.JsonParsingDate `json:"updatedAt,omitempty"`
	Uuid             string                `json:"uuid"`
}
