/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vloadbalancing

import (
	"github.com/vngcloud/terraform-provider-vngcloud/client/utils"
)

type Member struct {
	Address        string                `json:"address"`
	Backup         bool                  `json:"backup"`
	CreatedAt      utils.JsonParsingDate `json:"createdAt"`
	MonitorPort    int32                 `json:"monitorPort"`
	Name           string                `json:"name"`
	PoolId         string                `json:"poolId"`
	ProtocolPort   int32                 `json:"protocolPort"`
	SubnetId       string                `json:"subnetId"`
	TypeCreate     string                `json:"typeCreate"`
	UpdatedAt      utils.JsonParsingDate `json:"updatedAt,omitempty"`
	Uuid           string                `json:"uuid"`
	Weight         int32                 `json:"weight"`
	Status         string                `json:"displayStatus"`
	ProgressStatus string                `json:"progressStatus"`
}
