/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vloadbalancing

type CreateL7PolicyRequestV2 struct {
	// Action. This indicates how the listener will route traffic. The value can be REDIRECT_TO_POOL or REDIRECT_TO_URL.
	Action string `json:"action"`
	// Compare operation. The value can be CONTAINS or EQUAL_TO
	CompareType string `json:"compareType"`
	// Keep the query string or not.
	KeepQueryString *bool `json:"keepQueryString"`
	// Policy name. Only letters (a-z, A-Z, 0-9, '_', '.') are allowed and your input data must be between 6 and 20 characters.
	Name string `json:"name"`
	// Redirect HTTP code for redirecting to other URL.
	RedirectHttpCode *int32 `json:"redirectHttpCode"`
	// Pool for forwarding.
	RedirectPoolId *string `json:"redirectPoolId"`
	// URL for forwarding.
	RedirectUrl *string `json:"redirectUrl"`
	// Which attribute to compare. The value can be PATH or HOST_NAME
	Type_ string `json:"type"`
	// The value to compare with attribute.
	Value string `json:"value"`
}
