/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vloadbalancing

type ResizeLoadBalancerRequest struct {
	// Package ID
	PackageId string `json:"packageId"`
}
