/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vloadbalancing

import (
	"github.com/vngcloud/terraform-provider-vngcloud/client/utils"
)

type Pool struct {
	CreatedAt         utils.JsonParsingDate `json:"createdAt"`
	Description       string                `json:"description"`
	HealthMonitor     *HealthMonitor        `json:"healthMonitor,omitempty"`
	LoadBalanceMethod string                `json:"loadBalanceMethod"`
	Members           []Member              `json:"members,omitempty"`
	Name              string                `json:"name"`
	Status            string                `json:"displayStatus"`
	ProgressStatus    string                `json:"progressStatus"`
	Protocol          string                `json:"protocol"`
	Stickiness        bool                  `json:"stickiness"`
	TlsEncryption     bool                  `json:"tlsEncryption"`
	UpdatedAt         utils.JsonParsingDate `json:"updatedAt,omitempty"`
	Uuid              string                `json:"uuid"`
}
