/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vloadbalancing

type UpdateMembersRequestV2 struct {
	// List of members of the pool.
	Members []CreateMemberRequest `json:"members"`
}
