/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vloadbalancing

type UpdatePoolRequestV2 struct {
	// Algorithm of the pool. The algorithm can be \"ROUND_ROBIN\" or \"LEAST_CONNECTIONS\" or \"SOURCE_IP\"
	Algorithm string `json:"algorithm"`
	// Update request for health monitor
	HealthMonitor *UpdateHealthMonitorRequest `json:"healthMonitor"`
	// Enable sticky sessions.
	Stickiness *bool `json:"stickiness"`
	// Enable TLS encryption.
	TlsEncryption *bool `json:"tlsEncryption"`
}
