/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vdb

import (
	"time"
)

type DbInstanceInfo struct {
	Address              map[string][]AddressInfo `json:"address,omitempty"`
	AutoRenewPeriod      int32                    `json:"autoRenewPeriod,omitempty"`
	BackupAuto           bool                     `json:"backupAuto,omitempty"`
	BackupDuration       int32                    `json:"backupDuration,omitempty"`
	BackupTime           string                   `json:"backupTime,omitempty"`
	BackupUsage          float32                  `json:"backupUsage,omitempty"`
	Bandwidth            int32                    `json:"bandwidth,omitempty"`
	Configuration        *ConfigGroupPartialInfo  `json:"configuration,omitempty"`
	Cost                 float64                  `json:"cost,omitempty"`
	Created              string                   `json:"created,omitempty"`
	DatastoreType        string                   `json:"datastoreType,omitempty"`
	DatastoreVersion     string                   `json:"datastoreVersion,omitempty"`
	DbBackendId          int32                    `json:"dbBackendId,omitempty"`
	DisabledAt           time.Time                `json:"disabledAt,omitempty"`
	EnableAutoRenew      bool                     `json:"enableAutoRenew,omitempty"`
	EndTime              time.Time                `json:"endTime,omitempty"`
	EngineGroup          int32                    `json:"engineGroup,omitempty"`
	FreeBackupSize       int32                    `json:"freeBackupSize,omitempty"`
	Hostname             string                   `json:"hostname,omitempty"`
	Id                   string                   `json:"id,omitempty"`
	Ip                   []string                 `json:"ip,omitempty"`
	License              string                   `json:"license,omitempty"`
	Name                 string                   `json:"name,omitempty"`
	PackageName          string                   `json:"packageName,omitempty"`
	Period               int32                    `json:"period,omitempty"`
	Poc                  bool                     `json:"poc,omitempty"`
	Port                 int32                    `json:"port,omitempty"`
	PriceKey             string                   `json:"priceKey,omitempty"`
	ProjectId            string                   `json:"projectId,omitempty"`
	PublicAccess         bool                     `json:"publicAccess,omitempty"`
	QuotaPackageId       string                   `json:"quotaPackageId,omitempty"`
	Ram                  int32                    `json:"ram,omitempty"`
	RedisPasswordEnabled bool                     `json:"redisPasswordEnabled,omitempty"`
	ReplicaSourceId      string                   `json:"replicaSourceId,omitempty"`
	Replicas             []string                 `json:"replicas,omitempty"`
	Role                 string                   `json:"role,omitempty"`
	SecurityGroup        []SecurityGroupInfo      `json:"securityGroup,omitempty"`
	ServerId             string                   `json:"serverId,omitempty"`
	StartTime            time.Time                `json:"startTime,omitempty"`
	Status               string                   `json:"status,omitempty"`
	Updated              string                   `json:"updated,omitempty"`
	UserId               int32                    `json:"userId,omitempty"`
	Vcpus                int32                    `json:"vcpus,omitempty"`
	VolumeId             string                   `json:"volumeId,omitempty"`
	VolumeSize           int32                    `json:"volumeSize,omitempty"`
	VolumeType           string                   `json:"volumeType,omitempty"`
	VolumeTypeZoneId     string                   `json:"volumeTypeZoneId,omitempty"`
	VolumeUsed           float32                  `json:"volumeUsed,omitempty"`
	ZoneType             string                   `json:"zoneType,omitempty"`
	ZoneUUID             string                   `json:"zoneUUID,omitempty"`
}
