/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vdb

type ConfigParamInfo struct {
	Description     string   `json:"description,omitempty"`
	Max             string   `json:"max,omitempty"`
	Min             string   `json:"min,omitempty"`
	Modifiable      bool     `json:"modifiable,omitempty"`
	Name            string   `json:"name,omitempty"`
	RestartRequired bool     `json:"restartRequired,omitempty"`
	Type_           string   `json:"type,omitempty"`
	Values          []string `json:"values,omitempty"`
}
