/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vdb

type DeleteBackupStorageRequest struct {
	BackupStorageId   string      `json:"backupStorageId,omitempty"`
	BackupStorageName string      `json:"backupStorageName,omitempty"`
	EngineGroup       int32       `json:"engineGroup,omitempty"`
	Extra             interface{} `json:"extra,omitempty"`
	ProjectId         string      `json:"projectId,omitempty"`
}
