/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vdb

type DbAutoRenewChangeRequest struct {
	AutoRenewPeriod int32  `json:"autoRenewPeriod,omitempty"`
	DbInstanceId    string `json:"dbInstanceId,omitempty"`
	EnableAutoRenew bool   `json:"enableAutoRenew,omitempty"`
	ProjectId       string `json:"projectId,omitempty"`
}
